onprem 1.4 patch (#1009)

diff --git a/codefresh/files/on-prem/mongoSeedJobScript b/codefresh/files/on-prem/mongoSeedJobScript
--- a/codefresh/files/on-prem/mongoSeedJobScript
+++ b/codefresh/files/on-prem/mongoSeedJobScript
@@ -1,6 +1,34 @@
 #!/usr/bin/env bash
 
-set +e
+<<COMMENT
+Script is used to seed the inital data for onprem instance:
+
+export ASSETS_PATH=./assets/
+export MONGODB_URI=...
+export MONGODB_ROOT_USER=...
+export MONGODB_ROOT_PASSWORD=...
+
+./mongoSeedJobScript.sh
+
+COMMENT
+
+# set -eou pipefail
+
+MONGODB_DATABASES=(
+    "archive"
+    "charts-manager"
+    "cluster-providers"
+    "codefresh"
+    "context-manager"
+    "gitops-dashboard-manager"
+    "k8s-monitor"
+    "pipeline-manager"
+    "runtime-environment-manager"
+)
+
+disableMongoTelemetry() {
+    mongosh --nodb --eval "disableTelemetry()"
+}
 
 waitForMongoDB() {
     while true; do
@@ -21,7 +49,7 @@ parseMongoURI() {
     local parameters="$(echo $1 | grep '?' | cut -d '?' -f2)"; if [[ -n $parameters ]]; then parameters="?${parameters}"; fi
     local url="$(echo ${1/$proto/})"
     local userpass="$(echo $url | grep @ | cut -d@ -f1)"
-    local hostport="$(echo $url | sed s/$userpass// | sed "s/\/\?$parameters//" | sed -re "s/\/\?|@//g")"
+    local hostport="$(echo $url | sed s/$userpass// | sed "s/\/\?$parameters//" | sed -re "s/\/\?|@//g" | sed 's/\/$//')"
 
     MONGODB_PASSWORD="$(echo $userpass | grep : | cut -d: -f2)"
     MONGODB_USER="$(echo $userpass | grep : | cut -d: -f1)"
@@ -35,17 +63,14 @@ getMongoVersion() {
 
 parseMongoURI $MONGODB_URI
 
-if [[ -z "${MONGODB_ROOT_USER}" || -z "${MONGODB_ROOT_PASSWORD}" || -z "${MONGODB_URI}" || -z "${MONGODB_DATABASE}" || -z "${MONGODB_USER}" || -z "${MONGODB_PASSWORD}" ]]; then
-    echo "Some of the variables are not defined correctly. Check them out !"
-    exit 1
-fi
+disableMongoTelemetry
 
 waitForMongoDB
 
 getMongoVersion
 
-for db in ${MONGODB_DATABASE} "archive"; do
-    mongosh ${MONGODB_ROOT_URI} --eval "db.getSiblingDB('${db}').createUser({user: '${MONGODB_USER}', pwd: '${MONGODB_PASSWORD}', roles: ['readWrite']})" || echo "Error creating the user. Continuing anyway assuming the user is already created..."
+for MONGODB_DATABASE in ${MONGODB_DATABASES[@]}; do
+   mongosh ${MONGODB_ROOT_URI} --eval "db.getSiblingDB('${MONGODB_DATABASE}').createUser({user: '${MONGODB_USER}', pwd: '${MONGODB_PASSWORD}', roles: ['readWrite']})" || echo "Error creating the user. Continuing anyway assuming the user is already created..."
 done
 
 mongoimport --uri ${MONGODB_URI} --collection idps --type json --legacy --file /etc/admin/idps.json
